version: "3.2"
services:
  nodejs:
    build:
      context: .
    image: amakundu/nodejs-mysql-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=nil-mysql-app
      - MYSQL_USER=niluser
      - MYSQL_PASS=nilpass
      - MYSQL_DB=nil_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:3000"
    container_name: nil-nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=niluser
      - MYSQL_PASSWORD=nilpass
      - MYSQL_DATABASE=nil_db
    container_name: nil-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=nil-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: nil-phpmyadmin-app
networks:
  frontend:
  backend:
